# Generated by Django 6.1.1 on 2026-09-17 18:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('listing_type', models.CharField(choices=[('SALE', 'For Sale'), ('RENT', 'For Rent'), ('SERVICE', 'Academic Service'), ('DIGITAL', 'Digital Asset')], db_index=True, default='SALE', max_length=20)),
                ('condition', models.CharField(blank=True, choices=[('NEW', 'Brand New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20)),
                ('rental_period', models.CharField(blank=True, choices=[('DAY', 'Per Day'), ('MONTH', 'Per Month'), ('SEMESTER', 'Per Semester')], max_length=20)),
                ('location', models.CharField(blank=True, help_text='Campus building, department, or handover spot', max_length=150)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('RENTED', 'Rented'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='market.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.listing')),
            ],
            options={
                'verbose_name': 'Listing Image',
                'verbose_name_plural': 'Listing Images',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NeedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('request_type', models.CharField(choices=[('BUY', 'Wanted to Buy'), ('BORROW', 'Wanted to Borrow / Rent'), ('SERVICE', 'Seeking Tutoring / Academic Service')], db_index=True, default='BUY', max_length=20)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget in INR (leave blank if flexible or wanting to borrow)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_budget_negotiable', models.BooleanField(default=True)),
                ('urgency', models.CharField(choices=[('URGENT', 'Needed ASAP (Within 24-48 Hours)'), ('MODERATE', 'Needed This Week'), ('FLEXIBLE', 'Flexible / Anytime This Semester')], db_index=True, default='URGENT', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Campus meeting spot (e.g., Central Library, Tech Quad, Mess 2)', max_length=150)),
                ('description', models.TextField(help_text='Explain course context, exam deadline, required specs, or return timeline')),
                ('status', models.CharField(choices=[('OPEN', 'Active / Seeking'), ('FULFILLED', 'Fulfilled by Peer'), ('CLOSED', 'Closed / Expired')], db_index=True, default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='need_requests', to='market.category')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Need Request',
                'verbose_name_plural': 'Need Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NeedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Describe what you have, item condition, or availability')),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_offers', to=settings.AUTH_USER_MODEL)),
                ('need_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='market.needrequest')),
            ],
            options={
                'verbose_name': 'Need Offer',
                'verbose_name_plural': 'Need Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='market.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'status'], name='market_list_categor_da908a_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller', 'status'], name='market_list_seller__7dd93f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='market_list_price_3a149f_idx'),
        ),
        migrations.AddIndex(
            model_name='needrequest',
            index=models.Index(fields=['status', 'urgency'], name='market_need_status_47c46e_idx'),
        ),
        migrations.AddIndex(
            model_name='needrequest',
            index=models.Index(fields=['request_type', 'status'], name='market_need_request_ad9fcd_idx'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='unique_user_listing_wishlist'),
        ),
    ]
