# Generated by Django 6.1.1 on 2026-09-18 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listingimage",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="market.listing",
            ),
        ),
        migrations.AddField(
            model_name="needoffer",
            name="responder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="need_offers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="needrequest",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="need_requests",
                to="market.category",
            ),
        ),
        migrations.AddField(
            model_name="needrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="need_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="needoffer",
            name="need_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="market.needrequest",
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlisted_by",
                to="market.listing",
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["category", "status"], name="market_list_categor_da908a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["seller", "status"], name="market_list_seller__7dd93f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["price"], name="market_list_price_3a149f_idx"),
        ),
        migrations.AddIndex(
            model_name="needrequest",
            index=models.Index(
                fields=["status", "urgency"], name="market_need_status_47c46e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="needrequest",
            index=models.Index(
                fields=["request_type", "status"], name="market_need_request_ad9fcd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                fields=("user", "listing"), name="unique_user_listing_wishlist"
            ),
        ),
    ]
