# Generated by Django 6.1 on 2026-09-17 05:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('request_type', models.CharField(choices=[('BUY', 'Wanted to Buy'), ('BORROW', 'Wanted to Borrow / Rent'), ('SERVICE', 'Seeking Tutoring / Academic Service')], db_index=True, default='BUY', max_length=20)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget in INR (leave blank if flexible or wanting to borrow)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_budget_negotiable', models.BooleanField(default=True)),
                ('urgency', models.CharField(choices=[('URGENT', 'Needed ASAP (Within 24-48 Hours)'), ('MODERATE', 'Needed This Week'), ('FLEXIBLE', 'Flexible / Anytime This Semester')], db_index=True, default='URGENT', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Campus meeting spot (e.g., Central Library, Tech Quad, Mess 2)', max_length=150)),
                ('description', models.TextField(help_text='Explain course context, exam deadline, required specs, or return timeline')),
                ('status', models.CharField(choices=[('OPEN', 'Active / Seeking'), ('FULFILLED', 'Fulfilled by Peer'), ('CLOSED', 'Closed / Expired')], db_index=True, default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='need_requests', to='market.category')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Need Request',
                'verbose_name_plural': 'Need Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NeedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Describe what you have, item condition, or availability')),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_offers', to=settings.AUTH_USER_MODEL)),
                ('need_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='market.needrequest')),
            ],
            options={
                'verbose_name': 'Need Offer',
                'verbose_name_plural': 'Need Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='needrequest',
            index=models.Index(fields=['status', 'urgency'], name='market_need_status_47c46e_idx'),
        ),
        migrations.AddIndex(
            model_name='needrequest',
            index=models.Index(fields=['request_type', 'status'], name='market_need_request_ad9fcd_idx'),
        ),
    ]
