# Generated by Django 6.1 on 2026-08-29 06:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='package', help_text='Lucide icon name (e.g. laptop, smartphone, book-open, zap, cpu, gamepad-2, home)', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER', 'Order Notification'), ('RENTAL', 'Rental Notification'), ('VERIFICATION', 'Verification Update'), ('MATCHING_REQUEST', 'Matching Request Found'), ('REVIEW', 'Review Received'), ('DIGITAL_READY', 'Digital Asset Ready'), ('SYSTEM', 'System Announcement')], default='SYSTEM', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Campus Handover (COD)'), ('RAZORPAY', 'Razorpay Secure Payment')], default='COD', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('COMPLETED', 'Payment Completed'), ('FAILED', 'Payment Failed')], default='PENDING', max_length=20)),
                ('order_status', models.CharField(choices=[('PLACED', 'Order Placed'), ('CONFIRMED', 'Confirmed by Seller'), ('READY', 'Ready for Pickup / Handover'), ('COMPLETED', 'Completed & Handed Over'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('campus', models.CharField(max_length=200)),
                ('delivery_location_notes', models.TextField(blank=True, help_text='Hostel room, campus library, cafeteria, etc.')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price or base service fee in INR (₹)', max_digits=10)),
                ('product_type', models.CharField(choices=[('PHYSICAL', 'Physical Product'), ('DIGITAL', 'Digital Asset / Notes'), ('SERVICE', 'Academic Service')], default='PHYSICAL', max_length=20)),
                ('condition', models.CharField(choices=[('LIKE_NEW', 'Like New (Mint)'), ('GOOD', 'Good (Minor wear)'), ('FAIR', 'Fair (Functional)'), ('NOT_APPLICABLE', 'Not Applicable')], default='GOOD', max_length=20)),
                ('campus', models.CharField(default='Main Campus', max_length=200)),
                ('buy_or_rent', models.CharField(choices=[('BUY', 'Buy Only'), ('RENT', 'Rent Only'), ('BOTH', 'Buy or Rent')], default='BUY', max_length=10)),
                ('rent_daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Daily rental rate in INR (₹)', max_digits=10, null=True)),
                ('rent_monthly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rental rate in INR (₹)', max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_urgent', models.BooleanField(default=False, help_text='Urgent Moving-Out Clearance deal')),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('digital_file', models.FileField(blank=True, help_text='Protected asset file (ZIP, PDF, Code)', null=True, upload_to='digital_assets/')),
                ('sample_preview_pdf', models.FileField(blank=True, help_text='Safe preview sample for buyers', null=True, upload_to='samples/')),
                ('service_rate_type', models.CharField(blank=True, choices=[('FLAT', 'Flat Session Rate'), ('PER_HOUR', 'Hourly Rate')], max_length=20, null=True)),
                ('service_duration_info', models.CharField(blank=True, help_text='e.g. 1 hour session / Full Semester Guidance', max_length=100)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_rental', models.BooleanField(default=False)),
                ('item_type', models.CharField(default='PHYSICAL', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.product')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(help_text='e.g. Apple M1 8-Core / Intel Core i7-1185G7', max_length=150)),
                ('ram_gb', models.PositiveIntegerField(help_text='RAM in Gigabytes (e.g. 8, 16, 32)')),
                ('storage_gb', models.PositiveIntegerField(help_text='Storage in Gigabytes (e.g. 256, 512, 1024)')),
                ('storage_type', models.CharField(choices=[('NVME_SSD', 'NVMe SSD'), ('SSD', 'SATA SSD'), ('HDD', 'Hard Disk Drive'), ('UFS', 'UFS Fast Flash'), ('EMMC', 'eMMC')], default='NVME_SSD', max_length=20)),
                ('battery_health_percent', models.PositiveIntegerField(default=90, help_text='Battery Maximum Capacity % (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('usage_duration_months', models.PositiveIntegerField(default=12, help_text='Used duration in months')),
                ('display_specs', models.CharField(help_text='e.g. 13.3-inch Retina Display (2560x1600)', max_length=200)),
                ('graphics', models.CharField(blank=True, help_text='e.g. Integrated Apple 7-Core / NVIDIA RTX 3050', max_length=150)),
                ('operating_system', models.CharField(default='macOS / Windows 11', max_length=100)),
                ('extra_specs', models.TextField(blank=True, help_text='Ports, charger included, cycle count, warranty status')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electronics_spec', to='marketplace.product')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_downloads', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='marketplace.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_rental', models.BooleanField(default=False)),
                ('rental_days', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='marketplace.product')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('REQUESTED', 'Rental Requested'), ('APPROVED', 'Approved by Owner'), ('ACTIVE', 'Active / In Possession'), ('RETURN_DUE', 'Return Due Soon'), ('RETURNED', 'Successfully Returned'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Handover notes / condition check')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals_received', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='marketplace.product')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('FAKE', 'Fake or Counterfeit Product'), ('SCAM', 'Potential Scam / Overpriced Fraud'), ('INCORRECT', 'Incorrect Specification / Misleading'), ('DUPLICATE', 'Spam / Duplicate Listing'), ('INAPPROPRIATE', 'Inappropriate Content / Harassment'), ('OTHER', 'Other Violation')], max_length=30)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('REVIEWING', 'Under Review'), ('RESOLVED', 'Resolved (Action Taken)'), ('REJECTED', 'Rejected (No Violation)')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.product')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SemesterBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('semester', models.CharField(help_text='e.g. 5th Semester / 3rd Semester', max_length=100)),
                ('course', models.CharField(help_text='e.g. BCA / B.Tech CSE / Mechanical', max_length=150)),
                ('campus', models.CharField(default='Main Campus', max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='bundles/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('BOOK', 'Textbook'), ('NOTES', 'Handwritten / Printed Notes'), ('LAB_TOOL', 'Lab Equipment / Drafter Kit'), ('DIGITAL', 'Digital Study Material / Code'), ('OTHER', 'Study Aid / Calculator')], default='BOOK', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.semesterbundle')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(help_text='e.g. 4:00 PM - 5:00 PM', max_length=50)),
                ('rate_type', models.CharField(default='FLAT', max_length=20)),
                ('estimated_hours', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_notes', models.TextField(blank=True, help_text='Topics, problem statement, repository link')),
                ('status', models.CharField(choices=[('REQUESTED', 'Session Requested'), ('ACCEPTED', 'Accepted by Mentor/Tutor'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Session Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_requested', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_received', to=settings.AUTH_USER_MODEL)),
                ('service_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='marketplace.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Need 5th Sem DBMS textbook under ₹400', max_length=255)),
                ('description', models.TextField()),
                ('max_budget', models.DecimalField(decimal_places=2, help_text='Maximum budget in INR (₹)', max_digits=10)),
                ('campus', models.CharField(default='Main Campus', max_length=200)),
                ('contact_preference', models.CharField(choices=[('WHATSAPP', 'WhatsApp Direct Message'), ('IN_APP', 'CampusGrid In-App / Email')], default='WHATSAPP', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open Request'), ('MATCHED', 'Potential Seller Found'), ('CLOSED', 'Closed / Fulfilled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.category')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(default='Tech University Campus', help_text="User's College/University Campus", max_length=200)),
                ('phone_number', models.CharField(blank=True, help_text='Contact number', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp contact number (with country code e.g. 919876543210)', max_length=20)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified Student')], default='UNVERIFIED', max_length=20)),
                ('is_seller', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_verified_purchase', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.product')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.wishlist')),
            ],
            options={
                'unique_together': {('wishlist', 'product')},
            },
        ),
    ]
