# Generated by Django 6.1 on 2026-08-29 07:06

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, help_text='Protected asset file (ZIP, PDF, Code)', null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/aromal s/Desktop/prjt/protected_media')), upload_to='digital_assets/'),
        ),
    ]
